apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.nameOverride | default (include "examplechart.fullname" .) }}
  labels:
    {{- include "examplechart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "examplechart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "examplechart.name" . }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "examplechart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          volumeMounts:
            {{- if .Values.configMap.enabled }}
            - name: config-volume
              mountPath: /etc/config
              subPath: ""
            {{- end }}
      volumes:
        {{- if .Values.configMap.enabled }}
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name | default (include "examplechart.fullname" .) }}
        {{- end }}
